echo SYSTEM INFORMATION
echo Hello, $(whoami)
echo Current Date is = $(date)
echo Current Directory = $(pwd)
echo Network Name and Node Name = $(uname -n)
echo Kernel Name = $(uname -s)
echo Kernel Version = $(uname -v)
echo Kernel Release = $(uname -r)
echo Kernel OS = $(uname -o)
echo Processor Type = $(uname -p)
echo Kernel Machine Information = $(uname -m)
echo All Information = $(uname -a)
